# references: https://medium.com/prnd/github%EC%97%90%EC%84%9C-release-tag-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EB%A7%8C%EB%93%A4%EC%96%B4-%EC%A3%BC%EA%B8%B0-1%EB%B6%84%EB%A7%8C%EC%97%90-%EC%84%A4%EC%A0%95-5c09a383fb08

name: Release Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{env.BUILD_CONFIGURATION}} ${{ github.ref }}
          body: |
            Automated Release by GitHub Action CI
          draft: false
          prerelease: false
          
  build:
    name: Release Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Zip
        run: sudo apt-get install zip gzip tar
               
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Zip Artifacts
        run: zip ${{ github.ref }}.zip package.json readme.txt Ribe.UnityAnimTool.Editor.asmdef UnityAnimTool.url Editor /

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.ref }}.zip