name: Deploy Release

on: 
  workflow_dispatch:
  push:
    branches: master

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 자신의 Node.js 버전으로 변경

      - name: Install Dependencies
        run: npm install @actions/github

      - name: Read Version from package.json
        id: get_version
        run: |
          version=$(node -p "require('./path/to/your_project_directory/package.json').version")
          echo "Version from package.json: $version"
          echo "::set-output name=version::$version" # 버전 값을 출력하여 GitHub Actions에 전달

      - name: Create and Deploy Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 자동으로 제공되는 GitHub 액세스 토큰 사용
          TAG_NAME: ${{ github.event.inputs.tag_name }} # 수동 실행 시 입력한 태그 이름을 가져옴
        run: |
          version=$(/bin/echo ${{ steps.get_version.outputs.version }}) # GitHub Actions에서 버전 값을 가져옴
          node - << EOF
          const { execSync } = require('child_process');
          const { GitHub } = require('@actions/github');

          async function main() {
            try {
              const githubToken = process.env.GITHUB_TOKEN;
              const githubRepo = process.env.GITHUB_REPOSITORY;
              const tag = version;
              const projectName = 'UnityAnimTool';
              const releaseTitle = `UnityAnimTool_V${tag}`;
              const fileName = `${projectName}_${tag}.zip`;

              // 압축 파일 생성 (이 예시에서는 간단하게 zip으로 생성)
              execSync(`zip -r ${fileName} ./your_project_directory`);

              // GitHub 인스턴스 생성 및 레포지토리 가져오기
              const octokit = new GitHub(githubToken);
              const [owner, repo] = githubRepo.split('/');
              const repository = octokit.repo(owner, repo);

              // 릴리스 생성
              const release = await repository.releases.createRelease({
                tag_name: tag,
                name: releaseTitle,
                body: 'Release Notes',
              });

              // 릴리스에 파일 첨부
              await repository.releases.uploadReleaseAsset({
                release_id: release.data.id,
                name: fileName,
                data: require('fs').readFileSync(fileName),
              });

              // 압축 파일 제거
              require('fs').unlinkSync(fileName);
            } catch (error) {
              console.error('Error occurred during deployment:', error);
              process.exit(1);
            }
          }

          main();
          EOF
