name: Deploy Release

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 자신의 Node.js 버전으로 변경

      - name: Install Dependencies
        run: npm install @actions/github

      - name: Read Version from package.json
        id: get_version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "Version from package.json: $version"
          echo "::set-output name=version::$version" # 버전 값을 출력하여 GitHub Actions에 전달

      - name: Create and Deploy Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 자동으로 제공되는 GitHub 액세스 토큰 사용
        run: |
          echo "Current directory contents:"
          ls ../../
          version=$(/bin/echo ${{ steps.get_version.outputs.version }}) # GitHub Actions에서 버전 값을 가져옴
          node deploy_release.js # deploy_release.js 파일 실행
