# references: https://www.sysnet.pe.kr/2/0/12542
#             https://github.com/actions/create-release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{env.BUILD_CONFIGURATION}} ${{ github.ref }}
          body: |
            Automated Release by GitHub Action CI
          draft: false
          prerelease: false
          
  build:
    name: Release Build
    needs: create_release
    
    runs-on: ubuntu-latest
    steps:
      - name: Install Zip
        run: sudo apt-get install zip gzip tar
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Zip Artifacts
        run: zip ${{ github.ref }}.zip package.json readme.txt Ribe.UnityAnimTool.Editor.asmdef UnityAnimTool.url Editor /

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ github.ref }}.zip
          asset_name: ${{ github.ref }}.zip
          asset_content_type: application/zip